---
- name: Installing Nginx And configuration
  hosts: all
  become: true
  vars_files:
    - variables.vars
  tasks:
    - name: "Installing NginX, PHP"
      apt:
        name:
          - nginx
          - php7.2
          - php-mysql
        state: present
    - name: "Document root creation"
      file:
        path: "{{ document_root }}/{{ domain_name }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ owner }}"

    - name: "Copy conf file from local to nginx"
      template:
        src: ./virtualhost.conf.tmpl
        dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
      register: vhost_conf

    - name: "Create a symbolic link for nginx conf"
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}.conf"
        state: link

    - name: Remove  default file (delete file)
      when: vhost_conf.changed == true
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Remove  default file (delete file)
      when: vhost_conf.changed == true
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: "Stopping service apache2, if running"
      ignore_errors: yes
      service:
        name: apache2
        state: stopped

    - name: "service enabling"
      when: vhost_conf.changed == true
      service:
        name: nginx
        state: restarted
        enabled: true

    - name: "apt update"
      apt:
        update_cache: yes

    - name: "mysql - package Installation"
      apt:
        name:
          - mysql-server
          - python3-pymysql
          - mysql-client
          - php7.2-fpm
        state: present
        update_cache: yes
      
    - name: "mysql - restarting/enabling service"
      service:
        name: mysql
        state: restarted
        enabled: true
    - name: "Change the authentication plugin of MySQL root user to mysql_native_password"
      ignore_errors: true
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

    - name: Flush Privileges
      ignore_errors: true
      shell: mysql -u root -e 'FLUSH PRIVILEGES'
    
    - name: "mysql - update root password"
      ignore_errors: yes
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root }}"
        host_all: true

    - name: "mysql - removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        user: ""
        state: absent

    - name: "mysql - removing test database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        name: "test"
        state: absent


    - name: "mysql - creating database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_db }}"
        state: present

    - name: "mysql - creating user & password"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        user: "{{ mysql_user }}"
        password: "{{ mysql_db_password }}"
        host: "%"
        priv: '{{ mysql_db }}.*:ALL'

    - name: "Wordpress - Downloading Tar File"
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/wordpress.tar

    - name: "Wordpress - Extracting Wordpress.tar"
      unarchive:
        src: /tmp/wordpress.tar
        dest: /tmp/
        remote_src: true

    - name: "Wordpress - Copying Contents"
      copy:
        src: /tmp/wordpress/
        dest: "{{ document_root }}/{{ domain_name }}/"
        remote_src: true
        owner: "{{ owner }}"
        group: "{{ owner }}"

    - name: "Wordpress - Creating wp-config.php"
      template:
        src: wp-config.php.tmpl
        dest: "{{ document_root }}/{{ domain_name }}/wp-config.php"
        owner: "{{ owner }}"
        group: "{{ owner }}"


    - name: "Post-Installation Restart"
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - mysql

    - name: "Post-Installation Clean-Up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress
        - /tmp/wordpress.tar
